/**
 * Translation key constants for type-safe access to translations
 * Helps prevent typos and provides IDE autocomplete support
 */

export const TRANSLATION_KEYS = {
  // Navigation
  NAVIGATION_MAP: "navigation.map",
  NAVIGATION_ASSETS: "navigation.assets",
  NAVIGATION_DASHBOARD: "navigation.dashboard",
  NAVIGATION_ADMIN: "navigation.admin",
  NAVIGATION_USERS: "navigation.users",
  NAVIGATION_ROLES: "navigation.roles",
  NAVIGATION_PERMISSIONS: "navigation.permissions",
  NAVIGATION_PERMISSION_MATRIX: "navigation.permissionMatrix",
  NAVIGATION_AUDIT_LOGS: "navigation.auditLogs",
  NAVIGATION_IMPORT_EXPORT: "navigation.importExport",
  NAVIGATION_LOGOUT: "navigation.logout",
  NAVIGATION_SETTINGS: "navigation.settings",

  // Admin - Users
  ADMIN_USERS_TITLE: "admin.users.title",
  ADMIN_USERS_HEADING: "admin.users.heading",
  ADMIN_USERS_SEARCH: "admin.users.search",
  ADMIN_USERS_SEARCH_PLACEHOLDER: "admin.users.searchPlaceholder",
  ADMIN_USERS_ROLE_FILTER: "admin.users.roleFilter",
  ADMIN_USERS_ALL_ROLES: "admin.users.allRoles",
  ADMIN_USERS_FILTER: "admin.users.filter",
  ADMIN_USERS_USER_ROLE: "admin.users.userRole",
  ADMIN_USERS_MANAGER: "admin.users.manager",
  ADMIN_USERS_ADMIN: "admin.users.admin",
  ADMIN_USERS_PERMISSIONS: "admin.users.permissions",

  // Admin - Roles
  ADMIN_ROLES_TITLE: "admin.roles.title",
  ADMIN_ROLES_HEADING: "admin.roles.heading",
  ADMIN_ROLES_NAME: "admin.roles.name",
  ADMIN_ROLES_CODE: "admin.roles.code",
  ADMIN_ROLES_DESCRIPTION: "admin.roles.description",
  ADMIN_ROLES_PERMISSIONS: "admin.roles.permissions",

  // Admin - Permissions
  ADMIN_PERMISSIONS_TITLE: "admin.permissions.title",
  ADMIN_PERMISSIONS_HEADING: "admin.permissions.heading",
  ADMIN_PERMISSIONS_KEY: "admin.permissions.key",
  ADMIN_PERMISSIONS_GROUP: "admin.permissions.group",
  ADMIN_PERMISSIONS_NAME: "admin.permissions.name",
  ADMIN_PERMISSIONS_DESCRIPTION: "admin.permissions.description",

  // Admin - Audit Logs
  ADMIN_AUDIT_LOGS_TITLE: "admin.auditLogs.title",
  ADMIN_AUDIT_LOGS_HEADING: "admin.auditLogs.heading",
  ADMIN_AUDIT_LOGS_ACTION: "admin.auditLogs.action",
  ADMIN_AUDIT_LOGS_ACTION_PLACEHOLDER: "admin.auditLogs.actionPlaceholder",
  ADMIN_AUDIT_LOGS_ENTITY_TYPE: "admin.auditLogs.entityType",
  ADMIN_AUDIT_LOGS_ENTITY_TYPE_PLACEHOLDER: "admin.auditLogs.entityTypePlaceholder",
  ADMIN_AUDIT_LOGS_ACTOR_USER_ID: "admin.auditLogs.actorUserId",
  ADMIN_AUDIT_LOGS_ACTOR_USER_ID_PLACEHOLDER: "admin.auditLogs.actorUserIdPlaceholder",
  ADMIN_AUDIT_LOGS_FROM_DATE: "admin.auditLogs.fromDate",
  ADMIN_AUDIT_LOGS_TO_DATE: "admin.auditLogs.toDate",
  ADMIN_AUDIT_LOGS_FILTER: "admin.auditLogs.filter",
  ADMIN_AUDIT_LOGS_TIMESTAMP: "admin.auditLogs.timestamp",
  ADMIN_AUDIT_LOGS_ACTOR: "admin.auditLogs.actor",
  ADMIN_AUDIT_LOGS_ENTITY: "admin.auditLogs.entity",
  ADMIN_AUDIT_LOGS_CHANGES: "admin.auditLogs.changes",

  // Breadcrumb
  BREADCRUMB_ADMIN: "breadcrumb.admin",
  BREADCRUMB_HOME: "breadcrumb.home",

  // Common UI
  COMMON_SAVE: "common.save",
  COMMON_CANCEL: "common.cancel",
  COMMON_DELETE: "common.delete",
  COMMON_EDIT: "common.edit",
  COMMON_ADD: "common.add",
  COMMON_CREATE: "common.create",
  COMMON_UPDATE: "common.update",
  COMMON_REMOVE: "common.remove",
  COMMON_SEARCH: "common.search",
  COMMON_FILTER: "common.filter",
  COMMON_RESET: "common.reset",
  COMMON_APPLY: "common.apply",
  COMMON_CLOSE: "common.close",
  COMMON_BACK: "common.back",
  COMMON_NEXT: "common.next",
  COMMON_PREVIOUS: "common.previous",
  COMMON_LOADING: "common.loading",
  COMMON_ERROR: "common.error",
  COMMON_SUCCESS: "common.success",
  COMMON_WARNING: "common.warning",
  COMMON_INFO: "common.info",
  COMMON_RETRY: "common.retry",
  COMMON_CONFIRM: "common.confirm",
  COMMON_YES: "common.yes",
  COMMON_NO: "common.no",
  COMMON_OK: "common.ok",
  COMMON_SUBMIT: "common.submit",
  COMMON_EXPORT: "common.export",
  COMMON_IMPORT: "common.import",
  COMMON_DOWNLOAD: "common.download",
  COMMON_UPLOAD: "common.upload",
  COMMON_VIEW: "common.view",
  COMMON_DETAILS: "common.details",
  COMMON_ACTIONS: "common.actions",
  COMMON_STATUS: "common.status",
  COMMON_ACTIVE: "common.active",
  COMMON_INACTIVE: "common.inactive",
  COMMON_ENABLED: "common.enabled",
  COMMON_DISABLED: "common.disabled",
  COMMON_ALL: "common.all",
  COMMON_NONE: "common.none",
  COMMON_SELECT: "common.select",
  COMMON_SELECTED: "common.selected",
  COMMON_EMPTY: "common.empty",
  COMMON_NO_DATA: "common.noData",
  COMMON_NO_RESULTS: "common.noResults",
  COMMON_TOTAL: "common.total",
  COMMON_PAGE: "common.page",
  COMMON_OF: "common.of",
  COMMON_ITEMS: "common.items",
  COMMON_ITEMS_PER_PAGE: "common.itemsPerPage",
  COMMON_SHOWING: "common.showing",
  COMMON_TO: "common.to",
  COMMON_FROM: "common.from",
  COMMON_DATE: "common.date",
  COMMON_TIME: "common.time",
  COMMON_NAME: "common.name",
  COMMON_EMAIL: "common.email",
  COMMON_USERNAME: "common.username",
  COMMON_PASSWORD: "common.password",
  COMMON_CONFIRM_PASSWORD: "common.confirmPassword",
  COMMON_DESCRIPTION: "common.description",
  COMMON_NOTES: "common.notes",
  COMMON_CREATED_AT: "common.createdAt",
  COMMON_UPDATED_AT: "common.updatedAt",
  COMMON_CREATED_BY: "common.createdBy",
  COMMON_UPDATED_BY: "common.updatedBy",
  COMMON_ID: "common.id",
  COMMON_CODE: "common.code",
  COMMON_TYPE: "common.type",
  COMMON_CATEGORY: "common.category",
  COMMON_GROUP: "common.group",
  COMMON_VALUE: "common.value",
  COMMON_LABEL: "common.label",
  COMMON_PLACEHOLDER: "common.placeholder",
  COMMON_REQUIRED: "common.required",
  COMMON_OPTIONAL: "common.optional",
  COMMON_DEFAULT: "common.default",
  COMMON_CUSTOM: "common.custom",
  COMMON_OTHER: "common.other",
  COMMON_MORE: "common.more",
  COMMON_LESS: "common.less",
  COMMON_EXPAND: "common.expand",
  COMMON_COLLAPSE: "common.collapse",
  COMMON_SHOW: "common.show",
  COMMON_HIDE: "common.hide",
  COMMON_SORT: "common.sort",
  COMMON_ASCENDING: "common.ascending",
  COMMON_DESCENDING: "common.descending",
  COMMON_ASC: "common.asc",
  COMMON_DESC: "common.desc",

  // Permissions
  PERMISSIONS_MANAGE: "permissions.manage",
  PERMISSIONS_VIEW: "permissions.view",
  PERMISSIONS_CREATE: "permissions.create",
  PERMISSIONS_EDIT: "permissions.edit",
  PERMISSIONS_DELETE: "permissions.delete",
  PERMISSIONS_EXPORT: "permissions.export",
  PERMISSIONS_IMPORT: "permissions.import",
  PERMISSIONS_API_KEYS: "permissions.apiKeys",
  PERMISSIONS_BACKUPS: "permissions.backups",
  PERMISSIONS_CONFIG: "permissions.config",
  PERMISSIONS_LOGS: "permissions.logs",
  PERMISSIONS_ROLES: "permissions.roles",
  PERMISSIONS_USERS: "permissions.users",

  // Messages - Success
  MESSAGES_SUCCESS_SAVED: "messages.success.saved",
  MESSAGES_SUCCESS_CREATED: "messages.success.created",
  MESSAGES_SUCCESS_UPDATED: "messages.success.updated",
  MESSAGES_SUCCESS_DELETED: "messages.success.deleted",
  MESSAGES_SUCCESS_IMPORTED: "messages.success.imported",
  MESSAGES_SUCCESS_EXPORTED: "messages.success.exported",

  // Messages - Error
  MESSAGES_ERROR_SAVE_FAILED: "messages.error.saveFailed",
  MESSAGES_ERROR_CREATE_FAILED: "messages.error.createFailed",
  MESSAGES_ERROR_UPDATE_FAILED: "messages.error.updateFailed",
  MESSAGES_ERROR_DELETE_FAILED: "messages.error.deleteFailed",
  MESSAGES_ERROR_IMPORT_FAILED: "messages.error.importFailed",
  MESSAGES_ERROR_EXPORT_FAILED: "messages.error.exportFailed",
  MESSAGES_ERROR_LOAD_FAILED: "messages.error.loadFailed",
  MESSAGES_ERROR_UNAUTHORIZED: "messages.error.unauthorized",
  MESSAGES_ERROR_NOT_FOUND: "messages.error.notFound",
  MESSAGES_ERROR_SERVER_ERROR: "messages.error.serverError",
  MESSAGES_ERROR_NETWORK_ERROR: "messages.error.networkError",
  MESSAGES_ERROR_VALIDATION_ERROR: "messages.error.validationError",

  // Messages - Warning
  MESSAGES_WARNING_UNSAVED_CHANGES: "messages.warning.unsavedChanges",
  MESSAGES_WARNING_CONFIRM_DELETE: "messages.warning.confirmDelete",
  MESSAGES_WARNING_CONFIRM_ACTION: "messages.warning.confirmAction",

  // Messages - Info
  MESSAGES_INFO_LOADING: "messages.info.loading",
  MESSAGES_INFO_PROCESSING: "messages.info.processing",
  MESSAGES_INFO_NO_DATA: "messages.info.noData",
  MESSAGES_INFO_NO_RESULTS: "messages.info.noResults",

  // Form
  FORM_REQUIRED: "form.required",
  FORM_INVALID_EMAIL: "form.invalidEmail",
  FORM_PASSWORD_TOO_SHORT: "form.passwordTooShort",
  FORM_PASSWORD_MISMATCH: "form.passwordMismatch",
  FORM_INVALID_USERNAME: "form.invalidUsername",
  FORM_USERNAME_TAKEN: "form.usernameTaken",
  FORM_EMAIL_TAKEN: "form.emailTaken",
  FORM_INVALID_INPUT: "form.invalidInput",
  FORM_SELECT_OPTION: "form.selectOption",
  FORM_SELECT_AT_LEAST_ONE: "form.selectAtLeastOne",
  FORM_MAX_LENGTH: "form.maxLength",
  FORM_MIN_LENGTH: "form.minLength",

  // Table
  TABLE_ID: "table.id",
  TABLE_NAME: "table.name",
  TABLE_EMAIL: "table.email",
  TABLE_USERNAME: "table.username",
  TABLE_ROLE: "table.role",
  TABLE_STATUS: "table.status",
  TABLE_CREATED_AT: "table.createdAt",
  TABLE_UPDATED_AT: "table.updatedAt",
  TABLE_ACTIONS: "table.actions",
  TABLE_SELECT: "table.select",
  TABLE_SELECT_ALL: "table.selectAll",
  TABLE_DESELECT_ALL: "table.deselectAll",
  TABLE_NO_DATA: "table.noData",
  TABLE_LOADING: "table.loading",
  TABLE_ERROR: "table.error",

  // Pagination
  PAGINATION_PREVIOUS: "pagination.previous",
  PAGINATION_NEXT: "pagination.next",
  PAGINATION_FIRST: "pagination.first",
  PAGINATION_LAST: "pagination.last",
  PAGINATION_PAGE: "pagination.page",
  PAGINATION_OF: "pagination.of",
  PAGINATION_SHOWING: "pagination.showing",
  PAGINATION_TO: "pagination.to",
  PAGINATION_RESULTS: "pagination.results",

  // Filter
  FILTER_SEARCH: "filter.search",
  FILTER_FILTER: "filter.filter",
  FILTER_RESET: "filter.reset",
  FILTER_APPLY: "filter.apply",
  FILTER_CLEAR_ALL: "filter.clearAll",
  FILTER_NO_FILTERS: "filter.noFilters",
  FILTER_FILTER_BY: "filter.filterBy",
  FILTER_SORT_BY: "filter.sortBy",
  FILTER_ASCENDING: "filter.ascending",
  FILTER_DESCENDING: "filter.descending",

  // Roles
  ROLES_ADMIN: "roles.admin",
  ROLES_MANAGER: "roles.manager",
  ROLES_USER: "roles.user",
  ROLES_GUEST: "roles.guest",
  ROLES_VIEWER: "roles.viewer",
  ROLES_EDITOR: "roles.editor",
  ROLES_OWNER: "roles.owner",

  // Audit Log
  AUDIT_LOG_CREATED: "auditLog.created",
  AUDIT_LOG_UPDATED: "auditLog.updated",
  AUDIT_LOG_DELETED: "auditLog.deleted",
  AUDIT_LOG_VIEWED: "auditLog.viewed",
  AUDIT_LOG_EXPORTED: "auditLog.exported",
  AUDIT_LOG_IMPORTED: "auditLog.imported",
  AUDIT_LOG_LOGIN: "auditLog.login",
  AUDIT_LOG_LOGOUT: "auditLog.logout",
  AUDIT_LOG_ROLE_ASSIGNED: "auditLog.roleAssigned",
  AUDIT_LOG_ROLE_REMOVED: "auditLog.roleRemoved",
  AUDIT_LOG_PERMISSION_GRANTED: "auditLog.permissionGranted",
  AUDIT_LOG_PERMISSION_REVOKED: "auditLog.permissionRevoked",
  AUDIT_LOG_PASSWORD_CHANGED: "auditLog.passwordChanged",
  AUDIT_LOG_PROFILE_UPDATED: "auditLog.profileUpdated",
  AUDIT_LOG_SETTINGS_CHANGED: "auditLog.settingsChanged",

  // Entity Types
  ENTITY_TYPES_USER: "entityTypes.user",
  ENTITY_TYPES_ROLE: "entityTypes.role",
  ENTITY_TYPES_PERMISSION: "entityTypes.permission",
  ENTITY_TYPES_ASSET: "entityTypes.asset",
  ENTITY_TYPES_SETTINGS: "entityTypes.settings",
  ENTITY_TYPES_AUDIT_LOG: "entityTypes.auditLog",
  ENTITY_TYPES_API_KEY: "entityTypes.apiKey",
  ENTITY_TYPES_BACKUP: "entityTypes.backup",
  ENTITY_TYPES_CONFIG: "entityTypes.config"
};

/**
 * Namespace constants for organizing translations
 */
export const TRANSLATION_NAMESPACES = {
  NAVIGATION: "navigation",
  ADMIN: "admin",
  BREADCRUMB: "breadcrumb",
  COMMON: "common",
  PERMISSIONS: "permissions",
  MESSAGES: "messages",
  FORM: "form",
  TABLE: "table",
  PAGINATION: "pagination",
  FILTER: "filter",
  ROLES: "roles",
  AUDIT_LOG: "auditLog",
  ENTITY_TYPES: "entityTypes",
  DATETIME: "datetime",
  HELP: "help"
};
